class BaseDataframeFactory:
    SCHEMA = "RAW_DATA_LANDING.WMX_API_ALL_TABLES"
    CONTENT_PACKAGES_TABLE = f"{SCHEMA}.CONTENT_PACKAGES"
    READINGS_TABLE = f"{SCHEMA}.READINGS"
    SECTIONS_TABLE = f"{SCHEMA}.SECTIONS"
    QUESTIONS_TABLE = f"{SCHEMA}.QUESTIONS"
    FLASH_CARDS_TABLE = f"{SCHEMA}.FLASH_CARDS"
    TENANTS_TABLE = f"{SCHEMA}.TENANTS"